version: 2.1

jobs:
  generate-usage-report:
    docker:
      - image: python:3.9
    environment:
      # These values should be set in CircleCI project settings or contexts.
      ORG_ID: "your-org-id"
      USAGE_START_DATE: "2025-01-01"
      USAGE_END_DATE: "2025-02-28"
      # CIRCLECI_API_TOKEN should be set as an environment variable securely.
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install requests
      - run:
          name: Trigger and Fetch Usage Report
          command: |
            python generate_usage_report.py
      - store_artifacts:
          name: Archive Usage Report
          path: usage_report.json
          destination: usage_report

workflows:
  build:
    jobs:
      - generate-usage-report
